baseURL = 'https://distill-linux.github.io/'
languageCode = 'en-us'
title = 'distill - simple from-scratch linux'
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'distill is an independent, from-scratch x86-64 linux distribution based on musl, toybox, mksh, runit, drop/sink, and clang.'
  tagline = 'simple from-scratch linux'

[menu]
  [[menu.top]]
    name = 'git'
    url = 'https://github.com/distill-linux'
    weight = 10
  [[menu.top]]
    name = 'ports'
    url = '/ports/'
    weight = 20
  [[menu.top]]
    name = 'docs'
    url = '/docs/'
    weight = 30
  [[menu.top]]
    name = 'discord'
    url = 'https://discord.gg/distill'
    weight = 40

  [[menu.sidebar]]
    name = 'docs/'
    url = '/docs/'
    weight = 10
  [[menu.sidebar]]
    name = 'components/'
    url = '/components/'
    weight = 20
  [[menu.sidebar]]
    name = 'replacements/'
    url = '/replacements/'
    weight = 30
  [[menu.sidebar]]
    name = 'philosophy/'
    url = '/philosophy/'
    weight = 40
  [[menu.sidebar]]
    name = 'faq/'
    url = '/faq/'
    weight = 50
  [[menu.sidebar]]
    name = 'releases/'
    url = '/releases/'
    weight = 60
  [[menu.sidebar]]
    name = 'special-thanks/'
    url = '/special-thanks/'
    weight = 70

[markup.highlight]
  noClasses = false
  guessSyntax = false
